### ISSUE TITLE
Startup menu only works with mouse right click

### ISSUE THREAD

**Issue by alexandrehtrb** [rikka0w0/Menu98#1]
Hello,

I tested the project on my computer, a Windows 7 x64. It worked, but the menu only shows up when the Windows button receives a right click on it. Was it supposed to behave like that?

**Comment by rikka0w0** [comment]
Hi alexandrehtrb,

This is the behavior by design, I didn't hook the 'Win+X' shortcut key, currently there's no way to access the new menu by any form of keyboard shortcut, but I could add this feature in later releases, any recommendation?

**Comment by alexandrehtrb** [comment]
Hello,

Could the menu be shown when the button gets a left mouse click?
________________________________
De: Rikka0_0小六花<mailto:notifications@github.com>
Enviada em: ‎08/‎06/‎2019 14:36
Para: rikka0w0/Menu98<mailto:Menu98@noreply.github.com>
Cc: Alexandre H.T.R. Bonfitto<mailto:alexandrehtrb@outlook.com>; Author<mailto:author@noreply.github.com>
Assunto: Re: [rikka0w0/Menu98] Startup menu only works with mouse right click (#1)


Hi alexandrehtrb,

This is the behavior by design, I didn't hook the 'Win+X' shortcut key, currently there's no way to access the new menu by any form of keyboard shortcut, but I could add this feature in later releases, any recommendation?

**Comment by rikka0w0** [comment]
Yes, but in order to do that, you need to modify the code and recompile it.
In the program, search for WM_CONTEXTMENU message (responsible for right click) and then change them to WM_COMMAND (responsible for normal click).

**Comment by alexandrehtrb** [comment]
Thanks! Would you like that I opened a pull request for that?

Alexandre H. T. R. Bonfitto
________________________________
De: Rikka0_0小六花<mailto:notifications@github.com>
Enviada em: ‎10/‎06/‎2019 10:22
Para: rikka0w0/Menu98<mailto:Menu98@noreply.github.com>
Cc: Alexandre H.T.R. Bonfitto<mailto:alexandrehtrb@outlook.com>; Author<mailto:author@noreply.github.com>
Assunto: Re: [rikka0w0/Menu98] Startup menu only works with mouse right click (#1)


Yes, but in order to do that, you need to modify the code and recompile it.
In the program, search for WM_CONTEXTMENU message (responsible for right click) and then change them to WM_COMMAND (responsible for normal click).
